name: run detekt
on: 
  pull_request:

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: detekt
        run: ./gradlew detekt
          
      - uses: reviewdog/action-setup@v1
      
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}
        run: cat ./app/build/reports/detekt/detekt.xml
          | reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review" -level="info"
